context:
  version: "0.2.0"

package:
  name: "blazeseq"
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  # Let pixi-build-mojo handle the script internally 
  # OR if using rattler-build directly, keep it simple:
  script:
    - mkdir -p $PREFIX/lib/mojo
    - mojo package blazeseq -o $PREFIX/lib/mojo/blazeseq.mojopkg

requirements:
  build:
    - ${{ compiler('cxx') }} # Needed if any shim logic is triggered
    - mojo ==0.26.1.0
  host:
    - mojo ==0.26.1.0
    - rapidgzip-mojo >=0.1.0 # This MUST be a package, not a git link
  run:
    - mojo ==0.26.1.0
    - rapidgzip-mojo >=0.1.0