context:
  version: "0.2.0"
  mojo_version: "=0.26.1"

package:
  name: "blazeseq"
  version: ${{ version }}

source:
  path: .
  use_gitignore: true

build:
  number: 0
  script:
    - mojo package blazeseq -o ${{ PREFIX }}/lib/mojo/BlazeSeq.mojopkg

requirements:
  host:
    - max ${{ mojo_version }}
  run:
    - max ${{ mojo_version }}

tests:
  - script:
      - if: unix
        then:
          - mojo test -I ${{ PREFIX }}/lib/mojo/BlazeSeq.mojopkg tests/test_device_record.mojo
          - mojo test -I ${{ PREFIX }}/lib/mojo/BlazeSeq.mojopkg tests/test_iostream.mojo
    requirements:
      run:
        - max ${{ mojo_version }}
    files:
      recipe:
        - tests/test_device_record.mojo
        - tests/test_iostream.mojo

about:
  homepage: https://github.com/MoSafi2/BlazeSeq
  license: MIT
  license_file: LICENSE
  summary: Fast FASTQ parsing and GPU-accelerated sequencing utilities in Mojo.
  repository: https://github.com/MoSafi2/BlazeSeq

extra:
  maintainers: []
  project_name: blazeseq
