"""Type stub for blazeseq: ensures 'parser' and other exports are known to type checkers."""

from typing import Iterator, Protocol

class FastqRecordProtocol(Protocol):
    def id(self) -> str: ...
    def sequence(self) -> str: ...
    def quality(self) -> str: ...
    def __len__(self) -> int: ...
    def phred_scores(self) -> list[int]: ...

class FastqBatchProtocol(Protocol):
    def num_records(self) -> int: ...
    def get_record(self, index: int) -> FastqRecordProtocol: ...
    def __iter__(self) -> Iterator[FastqRecordProtocol]: ...

class ParserProtocol(Protocol):
    def has_more(self) -> bool: ...
    def next_record(self) -> FastqRecordProtocol: ...
    def next_ref_as_record(self) -> FastqRecordProtocol: ...
    def next_batch(self, max_records: int) -> FastqBatchProtocol: ...

def parser(
    path: str,
    quality_schema: str = "generic",
    parallelism: int = 4,
) -> ParserProtocol: ...
def create_parser(
    path: str,
    quality_schema: str = "generic",
    parallelism: int = 4,
) -> ParserProtocol: ...

FastqRecord: type[FastqRecordProtocol]
FastqBatch: type[FastqBatchProtocol]
FastqParser: type
FastqGZParser: type
