name: Package and release

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Release package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install modular
      run: |
        curl -s https://get.modular.com | sh -
        modular auth


    - name: Install Mojo
      run: modular install mojo

    - name: Add to PATH
      run: echo "/home/runner/.modular/pkg/packages.modular.com_mojo/bin" >> $GITHUB_PATH

    - name: Create package
      run: mojo package blazeseq -o blazeseq.mojopkg

    - name: Upload package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: blazeseq.mojopkg
        tag: ${{ github.ref }}
        overwrite: true